### ISSUE TITLE
"Implementing Health Checks with Docker Swarm" link is broken

### ISSUE THREAD

**Issue by 1ma** [spiddy/presentations#1]
It'd be really helpful if you could also share the sample Go app that you showcased during the presentation.

Thank you :+1:

**Comment by spiddy** [comment]
Sure,

I'll add it soon, alongside with the slides and the steps during the
presentation.



__
Dimitris Kapanidis
Founder

T/ +34 6780 49 780



Harbur Cloud Solutions SL. - Modernizing Software Delivery
Travessera de Gracia 294 Entlo. 1, 08025, Barcelona, Spain
https://www.harbur.io

NOTICE:  This e-mail and any attachments are confidential and intended
solely for the attention and use of the named addressee(s). If you are not
the intended recipient, be aware that any disclosure, copying, distribution
or use of this e-mail or any part of it, without the prior written consent
of Harbur Cloud Solutions SL. is prohibited and may be unlawful. If you
have received this e-mail in error, please notify immediately by returning
it to the sender and delete this copy from your system.

**Comment by spiddy** [comment]
Slides are added along with YouTube video

**Comment by spiddy** [comment]
code is at https://github.com/spiddy/coin
